In [1]:
import numpy as np

sim_records_dtype = np.dtype([
    ("game_scores", np.int32, (5, 13, 2))
])

record = np.zeros(1, dtype=sim_records_dtype)

record["game_scores"][0, 0, 0] = [1, 0]
record["game_scores"][0, 0, 1] = [2, 0]
record["game_scores"][0, 0, 2] = [2, 1]
record["game_scores"][0, 0, 3] = [3, 1]
record["game_scores"][0, 0, 4] = [4, 1]
record["game_scores"][0, 0, 5] = [4, 2]
record["game_scores"][0, 0, 6] = [5, 2]
record["game_scores"][0, 0, 7] = [5, 3]
record["game_scores"][0, 0, 8] = [6, 3]

print(record["game_scores"])

[[[[1 0]
   [2 0]
   [2 1]
   [3 1]
   [4 1]
   [4 2]
   [5 2]
   [5 3]
   [6 3]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]]
