1.	COUNT ELEMENT GREATER PREVIOUS AVERAGE
- Given an array of positive integers, return the number of elements that are strictly greater than the average of all previous elements. Skip the first element.
- Example
- Input:
  responseTimes = [100, 200, 150,300]
- Output :
  2



In [14]:
def count_ele_greater_avg(resp_times):
    # edge case handling , we use a guard clause
    n = len(resp_times)
    if n <=1 :
        return 0
    # define variables and stroe val    
    count = 0
    running_sum = resp_times[0]
    for i in range(1,n):
        if resp_times[i] > running_sum/i:
            count +=1
            running_sum +=resp_times[i]
    return count         



    

In [15]:
count_ele_greater_avg([100, 200, 150,300])

2

- Question 2 : FIND THE SMALLEST POSITIVE INTEGER 
- Given an unsorted array of integers, find the smallest positive integer not present in the array in O(n) time and O(1) extra space.
- Example
- Input:
  orderNumbers = [3, 4, -1, 1]
- Output :
2


In [21]:
def small_pos_int(arr):
    #look for values greater than zero in the arr
    valid_arr = set(x for x in arr if x >0)
    missing = 1
    #(provided the value of missing is in the positives set then keep adding until it isn’t)
    #This logic is used to find the smallest missing integer by adding 1 until it sums up to the smallest missing integer that is missing
    while missing  in valid_arr:
        missing +=1
    return missing



In [22]:
#small_pos_int( [3, 4, -1, 1])
small_pos_int( [1,2,3,4,5,6,9])

7

- Question 3 :Check Palindrome by Filtering Non-Letters
- Given a string containing letters, digits, and symbols, determine if it reads the same forwards and backwards when considering only alphabetic characters (case-insensitive).

- input : code = A1b2B!a


- output : 1



In [29]:
def palindrome(str_val):
    real_alpha_str = " ".join(x.lower() for x in str_val if x.isalpha())
    if real_alpha_str ==real_alpha_str[::-1]:
        return 1
    else:
        return 0



In [30]:
palindrome( "A1b2B!ayt")

0

- Check for Non-Identical String Rotation
-Given two strings s1 and s2, return 1 if s2 is a rotation of s1 but not identical to s1, otherwise return 0.

Example

-Input:

s1 = abcde
s2 = cdeab

- Output:

True

In [33]:
def non_id_rotatn(s1,s2):
    if len(s1) != len(s2):
        return 0
    if s1 == s2:
        return 0
    return 1 if s1 in (s1 + s2) else 0    

In [32]:
# check
s1 = "abcde" 
s2 = "cdeab"
print(s1 + s2)

abcdecdeab


In [34]:
non_id_rotatn(s1,s2)

1

In [ ]:
import numpy as np 
def split_into_three(values): 
    return np.split(np.array(values), 3) 
print(split_into_three([1,2,3,4,5,6])) 

In [2]:
def positions_greater_than_five(values): 
    arr = np.array(values) 
    return np.where(arr > 5) 
print(positions_greater_than_five([1,7,3,9,2,8])) 

(array([1, 3, 5], dtype=int64),)


In [3]:
import numpy as np 
def clip_values(values, low, high): 
    return np.clip(np.array(values), low, high) 
print(clip_values([1, 5, 10, 15, 20], 4, 12))

[ 4  5 10 12 12]


In [4]:
def replace_negatives(values): 
    arr = np.array(values) 
    arr[arr < 0] = 0 
    return arr 
print(replace_negatives([3, -1, 5, -7, 2]))

[3 0 5 0 2]


In [5]:
#convert numpy into a float array and reverse it

class Array_reverse:

    def create_array(self,s):
        arr = np.array(s.split(), dtype =float)
        return arr
    def reverse_arr(self,arr):
        rev= arr[::-1]
        return rev
    def solver(self,s):
        arr = self.create_array(s)
        return self.reverse_arr(arr)

In [6]:
print(Array_reverse().solver("1 2 3 4 -8 -10"))

[-10.  -8.   4.   3.   2.   1.]
