In [1]:
import numpy as np 
def split_into_three(values): 
    return np.split(np.array(values), 3) 
print(split_into_three([1,2,3,4,5,6])) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
def positions_greater_than_five(values): 
    arr = np.array(values) 
    return np.where(arr > 5) 
print(positions_greater_than_five([1,7,3,9,2,8])) 

(array([1, 3, 5], dtype=int64),)


In [3]:
import numpy as np 
def clip_values(values, low, high): 
    return np.clip(np.array(values), low, high) 
print(clip_values([1, 5, 10, 15, 20], 4, 12))

[ 4  5 10 12 12]


In [4]:
def replace_negatives(values): 
    arr = np.array(values) 
    arr[arr < 0] = 0 
    return arr 
print(replace_negatives([3, -1, 5, -7, 2]))

[3 0 5 0 2]


In [5]:
#convert numpy into a float array and reverse it

class Array_reverse:

    def create_array(self,s):
        arr = np.array(s.split(), dtype =float)
        return arr
    def reverse_arr(self,arr):
        rev= arr[::-1]
        return rev
    def solver(self,s):
        arr = self.create_array(s)
        return self.reverse_arr(arr)

In [6]:
print(Array_reverse().solver("1 2 3 4 -8 -10"))

[-10.  -8.   4.   3.   2.   1.]
